<a href="https://colab.research.google.com/github/Brithysetu/AtividadeDeRevisao/blob/main/30092024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# INICIO

In [ ]:
!curl ipecho.net/plain # Esse IP é para adicionar na rede do MySQL

35.229.172.79

In [ ]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.0.0-cp310-cp310-manylinux_2_17_x86_64.whl.metadata (2.0 kB)
Downloading mysql_connector_python-9.0.0-cp310-cp310-manylinux_2_17_x86_64.whl (19.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.3/19.3 MB 71.1 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.0.0

In [ ]:
!pip install pyspark

Collecting pyspark
  Downloading pyspark-3.5.3.tar.gz (317.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.3/317.3 MB 4.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.10/dist-packages (from pyspark) (0.10.9.7)
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.5.3-py2.py3-none-any.whl size=317840625 sha256=f9108b313c0e9ef5c3ab3af2d9f97139e466a8a9333b47184089775e415d9b9c
  Stored in directory: /root/.cache/pip/wheels/1b/3a/92/28b93e2fbfdbb07509ca4d6f50c5e407f48dce4ddbda69a4ab
Successfully built pyspark
Installing collected packages: pyspark
Successfully installed pyspark-3.5.3

In [ ]:
# pandas
import mysql.connector as mc
import pandas as pd

In [ ]:
# iniciar uma sessão local
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("ShowDoSQL").getOrCreate()

In [ ]:
# Verifica o SparkContext
print(spark)

# Exibe a Spark version
print(spark.version)

<pyspark.sql.session.SparkSession object at 0x7c1370d92e00>
3.5.3

In [ ]:
# Definir quais funcões sql pyspark vamos importar
from pyspark.sql.functions import *

In [ ]:
# Definir os parametros de conexao do mysql
host = '35.225.237.49' # IP PUBLICO DA SUA INSTANCIA DO MYSQL
user = 'root' # USUARIO
password = '' # Senha
database = 'locadora'

In [ ]:
# Função que ao ser chamada irá realizar a nossa consulta SQL, toda vez que
# For chamada passaremos a 'query' no parametro
def sqlQuery(consulta):
  connection = mc.connect(
    host=host,
    user=user,
    password=password,
    database=database
  ) # criar a conexão

  cursor = connection.cursor() # criar o cursor que vai realizar as acoes

  cursor.execute(consulta) # realizar a consulta

  result = cursor.fetchall() # guardar o resultado

  df = pd.DataFrame(result, columns=cursor.column_names) # criar o DataFrame

  cursor.close() # Encerrar o cursor

  connection.close() # Encerrar a conexão

  return df # retorna para fora da função o Dataframe resultante

In [ ]:
tables = sqlQuery('show tables')
display(tables)

  Tables_in_locadora
0            aluguel
1              carro
2            cliente

### **1-Selecione todos os dados da tabela cliente.**

In [ ]:
cliente = sqlQuery('SELECT * FROM cliente')
display(cliente)

    cliente_id               nome          cidade estado sexo estado_civil
0            1          Ana Silva       Sao Paulo     SP    F     Solteiro
1            2        Bruno Souza  Rio de Janeiro     RJ    M       Casado
2            3     Carlos Pereira  Belo Horizonte     MG    M     Solteiro
3            4       Daniela Lima       Sao Paulo     SP    F       Casado
4            5     Eduardo Santos        Curitiba     PR    M     Solteiro
5            6     Fernanda Alves    Porto Alegre     RS    F       Casado
6            7      Gabriel Costa        Salvador     BA    M     Solteiro
7            8       Helena Rocha          Recife     PE    F     Solteiro
8            9        Igor Mendes       Fortaleza     CE    M       Casado
9           10      Juliana Souza       Sao Paulo     SP    F     Solteiro
10          11      Luis Fernando       Sao Paulo     SP    M     Solteiro
11          12       Mariana Dias        Brasilia     DF    F       Casado
12          13      Nuno Oliveira          Manaus     AM    M       Casado
13          14       Olivia Nunes           Belem     PA    F     Solteiro
14          15        Pedro Ramos   Florianopolis     SC    M     Solteiro
15          16    Queila Ferreira       Sao Paulo     SP    F       Casado
16          17  Ricardo Goncalves         Goiania     GO    M       Casado
17          18      Sofia Martins         Vitoria     ES    F     Solteiro
18          19       Thiago Lopes    Campo Grande     MS    M       Casado
19          20       Alice Torres       Sao Paulo     SP    F     Solteiro

### ** 2- Liste todos os clientes que moram na cidade de "São Paulo".**

In [ ]:
List_cliente = sqlQuery (
    '''
       SELECT nome, cidade
       FROM cliente
       WHERE cidade = 'Sao Paulo'
        '''
)
display(List_cliente)

              nome     cidade
0        Ana Silva  Sao Paulo
1     Daniela Lima  Sao Paulo
2    Juliana Souza  Sao Paulo
3    Luis Fernando  Sao Paulo
4  Queila Ferreira  Sao Paulo
5     Alice Torres  Sao Paulo

**3- Liste todos os clientes ordenados pelo nome em ordem alfabética.**

In [ ]:
cliente_ordenado = sqlQuery (
    '''
      SELECT *
      FROM cliente
      ORDER BY nome ASC


        '''
)

display(cliente_ordenado)

    cliente_id               nome          cidade estado sexo estado_civil
0           20       Alice Torres       Sao Paulo     SP    F     Solteiro
1            1          Ana Silva       Sao Paulo     SP    F     Solteiro
2            2        Bruno Souza  Rio de Janeiro     RJ    M       Casado
3            3     Carlos Pereira  Belo Horizonte     MG    M     Solteiro
4            4       Daniela Lima       Sao Paulo     SP    F       Casado
5            5     Eduardo Santos        Curitiba     PR    M     Solteiro
6            6     Fernanda Alves    Porto Alegre     RS    F       Casado
7            7      Gabriel Costa        Salvador     BA    M     Solteiro
8            8       Helena Rocha          Recife     PE    F     Solteiro
9            9        Igor Mendes       Fortaleza     CE    M       Casado
10          10      Juliana Souza       Sao Paulo     SP    F     Solteiro
11          11      Luis Fernando       Sao Paulo     SP    M     Solteiro
12          12       Mariana Dias        Brasilia     DF    F       Casado
13          13      Nuno Oliveira          Manaus     AM    M       Casado
14          14       Olivia Nunes           Belem     PA    F     Solteiro
15          15        Pedro Ramos   Florianopolis     SC    M     Solteiro
16          16    Queila Ferreira       Sao Paulo     SP    F       Casado
17          17  Ricardo Goncalves         Goiania     GO    M       Casado
18          18      Sofia Martins         Vitoria     ES    F     Solteiro
19          19       Thiago Lopes    Campo Grande     MS    M       Casado

### 4-Liste todos os clientes cujo nome começa com a letra 'A'.**negrito**

In [ ]:
Nome_A = sqlQuery (
    '''
      SELECT *
      FROM cliente
      WHERE nome
      LIKE 'A%'


        '''
)

display(Nome_A)

   cliente_id          nome     cidade estado sexo estado_civil
0           1     Ana Silva  Sao Paulo     SP    F     Solteiro
1          20  Alice Torres  Sao Paulo     SP    F     Solteiro

### 5-Selecione os 3 primeiros registros da tabela cliente.

In [ ]:
tres_registro = sqlQuery (
    '''
      SELECT *
      FROM cliente
      LIMIT 3

        '''
)

display(tres_registro)

   cliente_id            nome          cidade estado sexo estado_civil
0           1       Ana Silva       Sao Paulo     SP    F     Solteiro
1           2     Bruno Souza  Rio de Janeiro     RJ    M       Casado
2           3  Carlos Pereira  Belo Horizonte     MG    M     Solteiro

## **6- Liste todos os carros que são da marca 'Ford' ou 'Fiat'.**

In [ ]:
marca = sqlQuery (
    '''
      SELECT *
      FROM carro
      WHERE marca = 'Ford' OR marca = 'Fiat'


        '''
)

display(marca)

   carro_id    modelo marca   valor
0         1    Fiesta  Ford  120.00
1         2        Ka  Ford  110.00
2         3     Palio  Fiat  100.00
3         4       Uno  Fiat   90.00
4        14  EcoSport  Ford  160.00
5        15     Siena  Fiat  120.00
6        16      Argo  Fiat  130.00
7        19    Ranger  Ford  250.00

7-Encontre todos os carros cujo valor está entre 100 e 150.

In [ ]:
valorentre = sqlQuery (
    '''
      SELECT *
      FROM carro
      WHERE valor
      BETWEEN 100 AND 150

        '''
)

display(valorentre)

   carro_id   modelo       marca   valor
0         1   Fiesta        Ford  120.00
1         2       Ka        Ford  110.00
2         3    Palio        Fiat  100.00
3         5     Onix   Chevrolet  130.00
4         6   Prisma   Chevrolet  140.00
5         9      Gol  Volkswagen  110.00
6        11     HB20     Hyundai  150.00
7        12  Sandero     Renault  100.00
8        15    Siena        Fiat  120.00
9        16     Argo        Fiat  130.00

8-Conte quantos aluguéis foram realizados.

In [ ]:
alugueis = sqlQuery (
    '''
      SELECT COUNT(*)
      AS total_aluguel
      FROM aluguel


        '''
)

display(alugueis)

   total_aluguel
0             50

9-Calcule o valor total de todos os carros disponíveis para aluguel.

In [ ]:
tt = sqlQuery (
    '''

     SELECT SUM(valor)
      FROM carro


        '''
)

display(tt)

  SUM(valor)
0    3050.00

10-Calcule o valor médio dos carros.

In [ ]:
valor_medio = sqlQuery (
    '''
      SELECT AVG(valor)
      AS valor_medio
      FROM carro

        '''
)

display(valor_medio)

  valor_medio
0  152.500000

11-Encontre o menor e o maior valor de aluguel de carros.

In [ ]:
valor_menor = sqlQuery (
    '''
      SELECT
      MIN(valor) AS menor_valor,
      MAX(valor) AS maior_valor
      FROM carro


        '''
)

display(valor_menor)

  menor_valor maior_valor
0       90.00      250.00

12-Liste os estados diferentes presentes na tabela cliente.

In [ ]:
distinct_estado = sqlQuery (
    '''
      SELECT DISTINCT estado
      FROM cliente


        '''
)

display(distinct_estado)

   estado
0      SP
1      RJ
2      MG
3      PR
4      RS
5      BA
6      PE
7      CE
8      DF
9      AM
10     PA
11     SC
12     GO
13     ES
14     MS

## **13-Agrupe os clientes por estado e conte quantos clientes existem em cada estado.**

In [ ]:
agrup_estado = sqlQuery (
    '''
     SELECT estado,
     COUNT(*) AS numero_de_clientes
     FROM cliente
     GROUP BY estado;

        '''
)

display(agrup_estado)

   estado  numero_de_clientes
0      SP                   6
1      RJ                   1
2      MG                   1
3      PR                   1
4      RS                   1
5      BA                   1
6      PE                   1
7      CE                   1
8      DF                   1
9      AM                   1
10     PA                   1
11     SC                   1
12     GO                   1
13     ES                   1
14     MS                   1

14-Liste os modelos de carros e o número de vezes que cada um foi alugado.

In [ ]:
model_aluguel = sqlQuery (
    '''
     SELECT * FROM aluguel
     '''
)

display(model_aluguel)

    aluguel_id  cliente_id  carro_id data_aluguel
0            1           1         5   2023-08-15
1            2           1         2   2023-09-01
2            3           1        14   2023-09-10
3            4           1         3   2023-09-21
4            5           2         8   2023-07-30
5            6           2        17   2023-08-10
6            7           2        14   2023-09-02
7            8           2         5   2023-09-25
8            9           3        15   2023-06-15
9           10           3         5   2023-09-05
10          11           4         5   2023-09-20
11          12           4        17   2023-08-18
12          13           4         2   2023-09-22
13          14           5         3   2023-07-20
14          15           5         7   2023-08-05
15          16           5        10   2023-09-15
16          17           5        12   2023-09-28
17          18           6        11   2023-08-08
18          19           6        13   2023-09-03
19          20           6         5   2023-09-28
20          21           7        18   2023-09-07
21          22           7        20   2023-09-27
22          23           7         9   2023-09-30
23          24           8        12   2023-07-22
24          25           8         6   2023-09-03
25          26           9         4   2023-07-12
26          27           9         1   2023-08-19
27          28          10         5   2023-09-25
28          29          10        13   2023-07-18
29          30          10        11   2023-09-12
30          31          11         1   2023-08-12
31          32          11         9   2023-09-18
32          33          12         6   2023-09-14
33          34          12        19   2023-09-25
34          35          13        19   2023-08-16
35          36          13        10   2023-09-20
36          37          14         2   2023-08-30
37          38          14        15   2023-09-10
38          39          15         7   2023-09-11
39          40          15        19   2023-09-15
40          41          16         6   2023-08-22
41          42          16         4   2023-09-29
42          43          17         5   2023-09-29
43          44          17        14   2023-09-10
44          45          18        16   2023-07-25
45          46          18         9   2023-08-30
46          47          19         8   2023-08-12
47          48          19        13   2023-09-04
48          49          20        16   2023-09-05
49          50          20         7   2023-09-28

In [ ]:
models_aluguel_carro = sqlQuery (
    '''
    SELECT c.modelo,
    COUNT(a.aluguel_id) AS numero_de_alugueis
    FROM aluguel a
    JOIN carro c ON a.carro_id = c.carro_id
    GROUP BY c.modelo;



        '''
)

display(models_aluguel_carro)

      modelo  numero_de_alugueis
0     Fiesta                   2
1         Ka                   3
2      Palio                   2
3        Uno                   2
4       Onix                   7
5     Prisma                   3
6    Corolla                   3
7      Civic                   2
8        Gol                   3
9      Jetta                   2
10      HB20                   2
11   Sandero                   2
12    Duster                   3
13  EcoSport                   3
14     Siena                   2
15      Argo                   2
16     Cruze                   2
17   Compass                   1
18    Ranger                   3
19      HR-V                   1

15-Liste o nome dos clientes e o número de aluguéis que cada um fez.

In [ ]:
cliente_aluguel = sqlQuery (
    '''
    SELECT c.nome,
    COUNT(a.aluguel_id) AS numero_de_alugueis
    FROM aluguel a
    JOIN cliente c
    ON a.cliente_id = c.cliente_id
    GROUP BY c.nome


        '''
)

display(cliente_aluguel)

                 nome  numero_de_alugueis
0           Ana Silva                   4
1         Bruno Souza                   4
2      Carlos Pereira                   2
3        Daniela Lima                   3
4      Eduardo Santos                   4
5      Fernanda Alves                   3
6       Gabriel Costa                   3
7        Helena Rocha                   2
8         Igor Mendes                   2
9       Juliana Souza                   3
10      Luis Fernando                   2
11       Mariana Dias                   2
12      Nuno Oliveira                   2
13       Olivia Nunes                   2
14        Pedro Ramos                   2
15    Queila Ferreira                   2
16  Ricardo Goncalves                   2
17      Sofia Martins                   2
18       Thiago Lopes                   2
19       Alice Torres                   2

16-Liste todos os aluguéis, mostrando o nome do cliente e o modelo do carro alugado

In [ ]:


cliente_aluguel_nome = sqlQuery (
    '''
    SELECT a.aluguel_id, cl.nome, c.modelo
    FROM aluguel a
    JOIN cliente cl ON a.cliente_id = cl.cliente_id
    JOIN carro c ON a.carro_id = c.carro_id;


        '''
)

display(cliente_aluguel_nome)

    aluguel_id               nome    modelo
0            1          Ana Silva      Onix
1            2          Ana Silva        Ka
2            3          Ana Silva  EcoSport
3            4          Ana Silva     Palio
4            5        Bruno Souza     Civic
5            6        Bruno Souza     Cruze
6            7        Bruno Souza  EcoSport
7            8        Bruno Souza      Onix
8            9     Carlos Pereira     Siena
9           10     Carlos Pereira      Onix
10          11       Daniela Lima      Onix
11          12       Daniela Lima     Cruze
12          13       Daniela Lima        Ka
13          14     Eduardo Santos     Palio
14          15     Eduardo Santos   Corolla
15          16     Eduardo Santos     Jetta
16          17     Eduardo Santos   Sandero
17          18     Fernanda Alves      HB20
18          19     Fernanda Alves    Duster
19          20     Fernanda Alves      Onix
20          21      Gabriel Costa   Compass
21          22      Gabriel Costa      HR-V
22          23      Gabriel Costa       Gol
23          24       Helena Rocha   Sandero
24          25       Helena Rocha    Prisma
25          26        Igor Mendes       Uno
26          27        Igor Mendes    Fiesta
27          28      Juliana Souza      Onix
28          29      Juliana Souza    Duster
29          30      Juliana Souza      HB20
30          31      Luis Fernando    Fiesta
31          32      Luis Fernando       Gol
32          33       Mariana Dias    Prisma
33          34       Mariana Dias    Ranger
34          35      Nuno Oliveira    Ranger
35          36      Nuno Oliveira     Jetta
36          37       Olivia Nunes        Ka
37          38       Olivia Nunes     Siena
38          39        Pedro Ramos   Corolla
39          40        Pedro Ramos    Ranger
40          41    Queila Ferreira    Prisma
41          42    Queila Ferreira       Uno
42          43  Ricardo Goncalves      Onix
43          44  Ricardo Goncalves  EcoSport
44          45      Sofia Martins      Argo
45          46      Sofia Martins       Gol
46          47       Thiago Lopes     Civic
47          48       Thiago Lopes    Duster
48          49       Alice Torres      Argo
49          50       Alice Torres   Corolla

17-Encontre os clientes que alugaram o carro com modelo 'Onix'.

In [ ]:



cliente_onix = sqlQuery (
    '''
    SELECT cl.cliente_id, cl.nome
    FROM aluguel a
    JOIN cliente cl ON a.cliente_id = cl.cliente_id
    JOIN carro c ON a.carro_id = c.carro_id
    WHERE c.modelo = 'Onix'

        '''
)

display(cliente_onix)

   cliente_id               nome
0           1          Ana Silva
1           2        Bruno Souza
2           3     Carlos Pereira
3           4       Daniela Lima
4           6     Fernanda Alves
5          10      Juliana Souza
6          17  Ricardo Goncalves

18-Liste os nomes dos clientes e as datas em que alugaram carros.

In [ ]:
cliente_datas = sqlQuery (
    '''
    SELECT cliente.nome, aluguel.data_aluguel
    FROM aluguel
    JOIN cliente
    ON aluguel.cliente_id = cliente.cliente_id

        '''
)

display(cliente_datas)

                 nome data_aluguel
0           Ana Silva   2023-08-15
1           Ana Silva   2023-09-01
2           Ana Silva   2023-09-10
3           Ana Silva   2023-09-21
4         Bruno Souza   2023-07-30
5         Bruno Souza   2023-08-10
6         Bruno Souza   2023-09-02
7         Bruno Souza   2023-09-25
8      Carlos Pereira   2023-06-15
9      Carlos Pereira   2023-09-05
10       Daniela Lima   2023-09-20
11       Daniela Lima   2023-08-18
12       Daniela Lima   2023-09-22
13     Eduardo Santos   2023-07-20
14     Eduardo Santos   2023-08-05
15     Eduardo Santos   2023-09-15
16     Eduardo Santos   2023-09-28
17     Fernanda Alves   2023-08-08
18     Fernanda Alves   2023-09-03
19     Fernanda Alves   2023-09-28
20      Gabriel Costa   2023-09-07
21      Gabriel Costa   2023-09-27
22      Gabriel Costa   2023-09-30
23       Helena Rocha   2023-07-22
24       Helena Rocha   2023-09-03
25        Igor Mendes   2023-07-12
26        Igor Mendes   2023-08-19
27      Juliana Souza   2023-09-25
28      Juliana Souza   2023-07-18
29      Juliana Souza   2023-09-12
30      Luis Fernando   2023-08-12
31      Luis Fernando   2023-09-18
32       Mariana Dias   2023-09-14
33       Mariana Dias   2023-09-25
34      Nuno Oliveira   2023-08-16
35      Nuno Oliveira   2023-09-20
36       Olivia Nunes   2023-08-30
37       Olivia Nunes   2023-09-10
38        Pedro Ramos   2023-09-11
39        Pedro Ramos   2023-09-15
40    Queila Ferreira   2023-08-22
41    Queila Ferreira   2023-09-29
42  Ricardo Goncalves   2023-09-29
43  Ricardo Goncalves   2023-09-10
44      Sofia Martins   2023-07-25
45      Sofia Martins   2023-08-30
46       Thiago Lopes   2023-08-12
47       Thiago Lopes   2023-09-04
48       Alice Torres   2023-09-05
49       Alice Torres   2023-09-28

19-Encontre o nome dos clientes e os modelos de carros que alugaram.

In [ ]:
nome_modelo = sqlQuery (
    '''
    SELECT cliente.nome, carro.modelo
    FROM aluguel
    JOIN cliente ON aluguel.cliente_id = cliente.cliente_id
    JOIN carro ON aluguel.carro_id = carro.carro_id

        '''
)

display(nome_modelo)

                 nome    modelo
0           Ana Silva      Onix
1           Ana Silva        Ka
2           Ana Silva  EcoSport
3           Ana Silva     Palio
4         Bruno Souza     Civic
5         Bruno Souza     Cruze
6         Bruno Souza  EcoSport
7         Bruno Souza      Onix
8      Carlos Pereira     Siena
9      Carlos Pereira      Onix
10       Daniela Lima      Onix
11       Daniela Lima     Cruze
12       Daniela Lima        Ka
13     Eduardo Santos     Palio
14     Eduardo Santos   Corolla
15     Eduardo Santos     Jetta
16     Eduardo Santos   Sandero
17     Fernanda Alves      HB20
18     Fernanda Alves    Duster
19     Fernanda Alves      Onix
20      Gabriel Costa   Compass
21      Gabriel Costa      HR-V
22      Gabriel Costa       Gol
23       Helena Rocha   Sandero
24       Helena Rocha    Prisma
25        Igor Mendes       Uno
26        Igor Mendes    Fiesta
27      Juliana Souza      Onix
28      Juliana Souza    Duster
29      Juliana Souza      HB20
30      Luis Fernando    Fiesta
31      Luis Fernando       Gol
32       Mariana Dias    Prisma
33       Mariana Dias    Ranger
34      Nuno Oliveira    Ranger
35      Nuno Oliveira     Jetta
36       Olivia Nunes        Ka
37       Olivia Nunes     Siena
38        Pedro Ramos   Corolla
39        Pedro Ramos    Ranger
40    Queila Ferreira    Prisma
41    Queila Ferreira       Uno
42  Ricardo Goncalves      Onix
43  Ricardo Goncalves  EcoSport
44      Sofia Martins      Argo
45      Sofia Martins       Gol
46       Thiago Lopes     Civic
47       Thiago Lopes    Duster
48       Alice Torres      Argo
49       Alice Torres   Corolla

20-Crie uma consulta que retorne o nome dos clientes e uma coluna adicional chamada status_civil que classifica os clientes como "Solteiro" ou "Casado

In [ ]:
loucura = sqlQuery (
    '''
    SELECT cliente.nome,
    CASE WHEN cliente.estado_civil = 'Solteiro' THEN 'Solteiro'
    WHEN cliente.estado_civil = 'Casado' THEN 'Casado'
    ELSE 'Outro'
    END AS status_civil
    FROM cliente;


        '''
)

display(loucura)

                 nome status_civil
0           Ana Silva     Solteiro
1         Bruno Souza       Casado
2      Carlos Pereira     Solteiro
3        Daniela Lima       Casado
4      Eduardo Santos     Solteiro
5      Fernanda Alves       Casado
6       Gabriel Costa     Solteiro
7        Helena Rocha     Solteiro
8         Igor Mendes       Casado
9       Juliana Souza     Solteiro
10      Luis Fernando     Solteiro
11       Mariana Dias       Casado
12      Nuno Oliveira       Casado
13       Olivia Nunes     Solteiro
14        Pedro Ramos     Solteiro
15    Queila Ferreira       Casado
16  Ricardo Goncalves       Casado
17      Sofia Martins     Solteiro
18       Thiago Lopes       Casado
19       Alice Torres     Solteiro

# **Extraindo tabelas do banco de dados para Pandas**

In [ ]:
tables = sqlQuery('show tables')
display(tables)

  Tables_in_locadora
0            aluguel
1              carro
2            cliente

In [ ]:
aluguel = sqlQuery('SELECT * FROM aluguel')
display(aluguel)

    aluguel_id  cliente_id  carro_id data_aluguel
0            1           1         5   2023-08-15
1            2           1         2   2023-09-01
2            3           1        14   2023-09-10
3            4           1         3   2023-09-21
4            5           2         8   2023-07-30
5            6           2        17   2023-08-10
6            7           2        14   2023-09-02
7            8           2         5   2023-09-25
8            9           3        15   2023-06-15
9           10           3         5   2023-09-05
10          11           4         5   2023-09-20
11          12           4        17   2023-08-18
12          13           4         2   2023-09-22
13          14           5         3   2023-07-20
14          15           5         7   2023-08-05
15          16           5        10   2023-09-15
16          17           5        12   2023-09-28
17          18           6        11   2023-08-08
18          19           6        13   2023-09-03
19          20           6         5   2023-09-28
20          21           7        18   2023-09-07
21          22           7        20   2023-09-27
22          23           7         9   2023-09-30
23          24           8        12   2023-07-22
24          25           8         6   2023-09-03
25          26           9         4   2023-07-12
26          27           9         1   2023-08-19
27          28          10         5   2023-09-25
28          29          10        13   2023-07-18
29          30          10        11   2023-09-12
30          31          11         1   2023-08-12
31          32          11         9   2023-09-18
32          33          12         6   2023-09-14
33          34          12        19   2023-09-25
34          35          13        19   2023-08-16
35          36          13        10   2023-09-20
36          37          14         2   2023-08-30
37          38          14        15   2023-09-10
38          39          15         7   2023-09-11
39          40          15        19   2023-09-15
40          41          16         6   2023-08-22
41          42          16         4   2023-09-29
42          43          17         5   2023-09-29
43          44          17        14   2023-09-10
44          45          18        16   2023-07-25
45          46          18         9   2023-08-30
46          47          19         8   2023-08-12
47          48          19        13   2023-09-04
48          49          20        16   2023-09-05
49          50          20         7   2023-09-28

In [ ]:
carro = sqlQuery('SELECT * FROM carro')
display(carro)

    carro_id    modelo       marca   valor
0          1    Fiesta        Ford  120.00
1          2        Ka        Ford  110.00
2          3     Palio        Fiat  100.00
3          4       Uno        Fiat   90.00
4          5      Onix   Chevrolet  130.00
5          6    Prisma   Chevrolet  140.00
6          7   Corolla      Toyota  200.00
7          8     Civic       Honda  210.00
8          9       Gol  Volkswagen  110.00
9         10     Jetta  Volkswagen  180.00
10        11      HB20     Hyundai  150.00
11        12   Sandero     Renault  100.00
12        13    Duster     Renault  160.00
13        14  EcoSport        Ford  160.00
14        15     Siena        Fiat  120.00
15        16      Argo        Fiat  130.00
16        17     Cruze   Chevrolet  180.00
17        18   Compass        Jeep  220.00
18        19    Ranger        Ford  250.00
19        20      HR-V       Honda  190.00

In [ ]:
cliente = sqlQuery('SELECT * FROM cliente')
display(cliente)

    cliente_id               nome          cidade estado sexo estado_civil
0            1          Ana Silva       Sao Paulo     SP    F     Solteiro
1            2        Bruno Souza  Rio de Janeiro     RJ    M       Casado
2            3     Carlos Pereira  Belo Horizonte     MG    M     Solteiro
3            4       Daniela Lima       Sao Paulo     SP    F       Casado
4            5     Eduardo Santos        Curitiba     PR    M     Solteiro
5            6     Fernanda Alves    Porto Alegre     RS    F       Casado
6            7      Gabriel Costa        Salvador     BA    M     Solteiro
7            8       Helena Rocha          Recife     PE    F     Solteiro
8            9        Igor Mendes       Fortaleza     CE    M       Casado
9           10      Juliana Souza       Sao Paulo     SP    F     Solteiro
10          11      Luis Fernando       Sao Paulo     SP    M     Solteiro
11          12       Mariana Dias        Brasilia     DF    F       Casado
12          13      Nuno Oliveira          Manaus     AM    M       Casado
13          14       Olivia Nunes           Belem     PA    F     Solteiro
14          15        Pedro Ramos   Florianopolis     SC    M     Solteiro
15          16    Queila Ferreira       Sao Paulo     SP    F       Casado
16          17  Ricardo Goncalves         Goiania     GO    M       Casado
17          18      Sofia Martins         Vitoria     ES    F     Solteiro
18          19       Thiago Lopes    Campo Grande     MS    M       Casado
19          20       Alice Torres       Sao Paulo     SP    F     Solteiro

### **Convertendo os Dataframes em Pandas para Dataframes em PySpark**

In [ ]:
aluguel_ps = spark.createDataFrame(aluguel.to_dict('records'))
aluguel_ps.show()

+----------+--------+----------+------------+
|aluguel_id|carro_id|cliente_id|data_aluguel|
+----------+--------+----------+------------+
|         1|       5|         1|  2023-08-15|
|         2|       2|         1|  2023-09-01|
|         3|      14|         1|  2023-09-10|
|         4|       3|         1|  2023-09-21|
|         5|       8|         2|  2023-07-30|
|         6|      17|         2|  2023-08-10|
|         7|      14|         2|  2023-09-02|
|         8|       5|         2|  2023-09-25|
|         9|      15|         3|  2023-06-15|
|        10|       5|         3|  2023-09-05|
|        11|       5|         4|  2023-09-20|
|        12|      17|         4|  2023-08-18|
|        13|       2|         4|  2023-09-22|
|        14|       3|         5|  2023-07-20|
|        15|       7|         5|  2023-08-05|
|        16|      10|         5|  2023-09-15|
|        17|      12|         5|  2023-09-28|
|        18|      11|         6|  2023-08-08|
|        19|      13|         6|  2023-09-03|
|        20|       5|         6|  2023-09-28|
+----------+--------+----------+------------+
only showing top 20 rows

In [ ]:
carro_ps = spark.createDataFrame(carro.to_dict('records'))
carro_ps.show()

+--------+----------+--------+--------------------+
|carro_id|     marca|  modelo|               valor|
+--------+----------+--------+--------------------+
|       1|      Ford|  Fiesta|120.0000000000000...|
|       2|      Ford|      Ka|110.0000000000000...|
|       3|      Fiat|   Palio|100.0000000000000...|
|       4|      Fiat|     Uno|90.00000000000000...|
|       5| Chevrolet|    Onix|130.0000000000000...|
|       6| Chevrolet|  Prisma|140.0000000000000...|
|       7|    Toyota| Corolla|200.0000000000000...|
|       8|     Honda|   Civic|210.0000000000000...|
|       9|Volkswagen|     Gol|110.0000000000000...|
|      10|Volkswagen|   Jetta|180.0000000000000...|
|      11|   Hyundai|    HB20|150.0000000000000...|
|      12|   Renault| Sandero|100.0000000000000...|
|      13|   Renault|  Duster|160.0000000000000...|
|      14|      Ford|EcoSport|160.0000000000000...|
|      15|      Fiat|   Siena|120.0000000000000...|
|      16|      Fiat|    Argo|130.0000000000000...|
|      17| Chevrolet|   Cruze|180.0000000000000...|
|      18|      Jeep| Compass|220.0000000000000...|
|      19|      Ford|  Ranger|250.0000000000000...|
|      20|     Honda|    HR-V|190.0000000000000...|
+--------+----------+--------+--------------------+

In [ ]:
cliente_ps = spark.createDataFrame(cliente.to_dict('records'))
cliente_ps.show()

+--------------+----------+------+------------+-----------------+----+
|        cidade|cliente_id|estado|estado_civil|             nome|sexo|
+--------------+----------+------+------------+-----------------+----+
|     Sao Paulo|         1|    SP|    Solteiro|        Ana Silva|   F|
|Rio de Janeiro|         2|    RJ|      Casado|      Bruno Souza|   M|
|Belo Horizonte|         3|    MG|    Solteiro|   Carlos Pereira|   M|
|     Sao Paulo|         4|    SP|      Casado|     Daniela Lima|   F|
|      Curitiba|         5|    PR|    Solteiro|   Eduardo Santos|   M|
|  Porto Alegre|         6|    RS|      Casado|   Fernanda Alves|   F|
|      Salvador|         7|    BA|    Solteiro|    Gabriel Costa|   M|
|        Recife|         8|    PE|    Solteiro|     Helena Rocha|   F|
|     Fortaleza|         9|    CE|      Casado|      Igor Mendes|   M|
|     Sao Paulo|        10|    SP|    Solteiro|    Juliana Souza|   F|
|     Sao Paulo|        11|    SP|    Solteiro|    Luis Fernando|   M|
|      Brasilia|        12|    DF|      Casado|     Mariana Dias|   F|
|        Manaus|        13|    AM|      Casado|    Nuno Oliveira|   M|
|         Belem|        14|    PA|    Solteiro|     Olivia Nunes|   F|
| Florianopolis|        15|    SC|    Solteiro|      Pedro Ramos|   M|
|     Sao Paulo|        16|    SP|      Casado|  Queila Ferreira|   F|
|       Goiania|        17|    GO|      Casado|Ricardo Goncalves|   M|
|       Vitoria|        18|    ES|    Solteiro|    Sofia Martins|   F|
|  Campo Grande|        19|    MS|      Casado|     Thiago Lopes|   M|
|     Sao Paulo|        20|    SP|    Solteiro|     Alice Torres|   F|
+--------------+----------+------+------------+-----------------+----+

# **Criar as Views dos DataFrames em PySpark**

In [ ]:
# Registrando a View de categoriasv
cliente_ps.createOrReplaceTempView('clientesv')

# Registrando a View de clientesv
carro_ps.createOrReplaceTempView('carrosv')

# Registrando a View de fornecedoresv
aluguel_ps.createOrReplaceTempView('alugueisv')

In [ ]:
# Equivalente PySpark
# Acessa o Dataframe criado anteriormente e realiza a ação
dfps = cliente_ps.select('*')
dfps.show()

+--------------+----------+------+------------+-----------------+----+
|        cidade|cliente_id|estado|estado_civil|             nome|sexo|
+--------------+----------+------+------------+-----------------+----+
|     Sao Paulo|         1|    SP|    Solteiro|        Ana Silva|   F|
|Rio de Janeiro|         2|    RJ|      Casado|      Bruno Souza|   M|
|Belo Horizonte|         3|    MG|    Solteiro|   Carlos Pereira|   M|
|     Sao Paulo|         4|    SP|      Casado|     Daniela Lima|   F|
|      Curitiba|         5|    PR|    Solteiro|   Eduardo Santos|   M|
|  Porto Alegre|         6|    RS|      Casado|   Fernanda Alves|   F|
|      Salvador|         7|    BA|    Solteiro|    Gabriel Costa|   M|
|        Recife|         8|    PE|    Solteiro|     Helena Rocha|   F|
|     Fortaleza|         9|    CE|      Casado|      Igor Mendes|   M|
|     Sao Paulo|        10|    SP|    Solteiro|    Juliana Souza|   F|
|     Sao Paulo|        11|    SP|    Solteiro|    Luis Fernando|   M|
|      Brasilia|        12|    DF|      Casado|     Mariana Dias|   F|
|        Manaus|        13|    AM|      Casado|    Nuno Oliveira|   M|
|         Belem|        14|    PA|    Solteiro|     Olivia Nunes|   F|
| Florianopolis|        15|    SC|    Solteiro|      Pedro Ramos|   M|
|     Sao Paulo|        16|    SP|      Casado|  Queila Ferreira|   F|
|       Goiania|        17|    GO|      Casado|Ricardo Goncalves|   M|
|       Vitoria|        18|    ES|    Solteiro|    Sofia Martins|   F|
|  Campo Grande|        19|    MS|      Casado|     Thiago Lopes|   M|
|     Sao Paulo|        20|    SP|    Solteiro|     Alice Torres|   F|
+--------------+----------+------+------------+-----------------+----+

In [ ]:
# 1 Selecione todos os dados da tabela cliente
sql1 = spark.sql("SELECT * FROM clientesv")
sql1.show()

+--------------+----------+------+------------+-----------------+----+
|        cidade|cliente_id|estado|estado_civil|             nome|sexo|
+--------------+----------+------+------------+-----------------+----+
|     Sao Paulo|         1|    SP|    Solteiro|        Ana Silva|   F|
|Rio de Janeiro|         2|    RJ|      Casado|      Bruno Souza|   M|
|Belo Horizonte|         3|    MG|    Solteiro|   Carlos Pereira|   M|
|     Sao Paulo|         4|    SP|      Casado|     Daniela Lima|   F|
|      Curitiba|         5|    PR|    Solteiro|   Eduardo Santos|   M|
|  Porto Alegre|         6|    RS|      Casado|   Fernanda Alves|   F|
|      Salvador|         7|    BA|    Solteiro|    Gabriel Costa|   M|
|        Recife|         8|    PE|    Solteiro|     Helena Rocha|   F|
|     Fortaleza|         9|    CE|      Casado|      Igor Mendes|   M|
|     Sao Paulo|        10|    SP|    Solteiro|    Juliana Souza|   F|
|     Sao Paulo|        11|    SP|    Solteiro|    Luis Fernando|   M|
|      Brasilia|        12|    DF|      Casado|     Mariana Dias|   F|
|        Manaus|        13|    AM|      Casado|    Nuno Oliveira|   M|
|         Belem|        14|    PA|    Solteiro|     Olivia Nunes|   F|
| Florianopolis|        15|    SC|    Solteiro|      Pedro Ramos|   M|
|     Sao Paulo|        16|    SP|      Casado|  Queila Ferreira|   F|
|       Goiania|        17|    GO|      Casado|Ricardo Goncalves|   M|
|       Vitoria|        18|    ES|    Solteiro|    Sofia Martins|   F|
|  Campo Grande|        19|    MS|      Casado|     Thiago Lopes|   M|
|     Sao Paulo|        20|    SP|    Solteiro|     Alice Torres|   F|
+--------------+----------+------+------------+-----------------+----+

In [ ]:
# 2 Liste todos os clientes que moram na cidade de "São Paulo".
 # Spark SQL
sql2 = spark.sql(
    '''
      SELECT nome, cidade
       FROM clientesv
       WHERE cidade = 'Sao Paulo'
       '''
       )

sql2.show()

+---------------+---------+
|           nome|   cidade|
+---------------+---------+
|      Ana Silva|Sao Paulo|
|   Daniela Lima|Sao Paulo|
|  Juliana Souza|Sao Paulo|
|  Luis Fernando|Sao Paulo|
|Queila Ferreira|Sao Paulo|
|   Alice Torres|Sao Paulo|
+---------------+---------+

In [ ]:
# Equivalente PySpark
# Acessa o Dataframe criado anteriormente e realiza a ação


dfps = cliente_ps.filter(cliente_ps.cidade == 'Sao Paulo').select('nome', 'cidade')
dfps.show()

+---------------+---------+
|           nome|   cidade|
+---------------+---------+
|      Ana Silva|Sao Paulo|
|   Daniela Lima|Sao Paulo|
|  Juliana Souza|Sao Paulo|
|  Luis Fernando|Sao Paulo|
|Queila Ferreira|Sao Paulo|
|   Alice Torres|Sao Paulo|
+---------------+---------+

In [ ]:
# 3 Liste todos os clientes ordenados pelo nome em ordem alfabética.
sql3 = spark.sql(
    '''
      SELECT *
      FROM clientesv
      ORDER BY nome ASC
       '''
       )

sql3.show()

+--------------+----------+------+------------+-----------------+----+
|        cidade|cliente_id|estado|estado_civil|             nome|sexo|
+--------------+----------+------+------------+-----------------+----+
|     Sao Paulo|        20|    SP|    Solteiro|     Alice Torres|   F|
|     Sao Paulo|         1|    SP|    Solteiro|        Ana Silva|   F|
|Rio de Janeiro|         2|    RJ|      Casado|      Bruno Souza|   M|
|Belo Horizonte|         3|    MG|    Solteiro|   Carlos Pereira|   M|
|     Sao Paulo|         4|    SP|      Casado|     Daniela Lima|   F|
|      Curitiba|         5|    PR|    Solteiro|   Eduardo Santos|   M|
|  Porto Alegre|         6|    RS|      Casado|   Fernanda Alves|   F|
|      Salvador|         7|    BA|    Solteiro|    Gabriel Costa|   M|
|        Recife|         8|    PE|    Solteiro|     Helena Rocha|   F|
|     Fortaleza|         9|    CE|      Casado|      Igor Mendes|   M|
|     Sao Paulo|        10|    SP|    Solteiro|    Juliana Souza|   F|
|     Sao Paulo|        11|    SP|    Solteiro|    Luis Fernando|   M|
|      Brasilia|        12|    DF|      Casado|     Mariana Dias|   F|
|        Manaus|        13|    AM|      Casado|    Nuno Oliveira|   M|
|         Belem|        14|    PA|    Solteiro|     Olivia Nunes|   F|
| Florianopolis|        15|    SC|    Solteiro|      Pedro Ramos|   M|
|     Sao Paulo|        16|    SP|      Casado|  Queila Ferreira|   F|
|       Goiania|        17|    GO|      Casado|Ricardo Goncalves|   M|
|       Vitoria|        18|    ES|    Solteiro|    Sofia Martins|   F|
|  Campo Grande|        19|    MS|      Casado|     Thiago Lopes|   M|
+--------------+----------+------+------------+-----------------+----+

In [ ]:
# Equivalente PySpark
# Liste todos os clientes ordenados pelo nome em ordem alfabética.
# Acessa o Dataframe criado anteriormente e realiza a ação


dfps = cliente_ps.orderBy('nome')
dfps.show()

+--------------+----------+------+------------+-----------------+----+
|        cidade|cliente_id|estado|estado_civil|             nome|sexo|
+--------------+----------+------+------------+-----------------+----+
|     Sao Paulo|        20|    SP|    Solteiro|     Alice Torres|   F|
|     Sao Paulo|         1|    SP|    Solteiro|        Ana Silva|   F|
|Rio de Janeiro|         2|    RJ|      Casado|      Bruno Souza|   M|
|Belo Horizonte|         3|    MG|    Solteiro|   Carlos Pereira|   M|
|     Sao Paulo|         4|    SP|      Casado|     Daniela Lima|   F|
|      Curitiba|         5|    PR|    Solteiro|   Eduardo Santos|   M|
|  Porto Alegre|         6|    RS|      Casado|   Fernanda Alves|   F|
|      Salvador|         7|    BA|    Solteiro|    Gabriel Costa|   M|
|        Recife|         8|    PE|    Solteiro|     Helena Rocha|   F|
|     Fortaleza|         9|    CE|      Casado|      Igor Mendes|   M|
|     Sao Paulo|        10|    SP|    Solteiro|    Juliana Souza|   F|
|     Sao Paulo|        11|    SP|    Solteiro|    Luis Fernando|   M|
|      Brasilia|        12|    DF|      Casado|     Mariana Dias|   F|
|        Manaus|        13|    AM|      Casado|    Nuno Oliveira|   M|
|         Belem|        14|    PA|    Solteiro|     Olivia Nunes|   F|
| Florianopolis|        15|    SC|    Solteiro|      Pedro Ramos|   M|
|     Sao Paulo|        16|    SP|      Casado|  Queila Ferreira|   F|
|       Goiania|        17|    GO|      Casado|Ricardo Goncalves|   M|
|       Vitoria|        18|    ES|    Solteiro|    Sofia Martins|   F|
|  Campo Grande|        19|    MS|      Casado|     Thiago Lopes|   M|
+--------------+----------+------+------------+-----------------+----+

In [ ]:
# 4 Liste todos os clientes cujo nome começa com a letra 'A'.
sql4 = spark.sql(
    '''
       SELECT *
      FROM clientesv
      WHERE nome
      LIKE 'A%'
       '''
       )

sql4.show()

+---------+----------+------+------------+------------+----+
|   cidade|cliente_id|estado|estado_civil|        nome|sexo|
+---------+----------+------+------------+------------+----+
|Sao Paulo|         1|    SP|    Solteiro|   Ana Silva|   F|
|Sao Paulo|        20|    SP|    Solteiro|Alice Torres|   F|
+---------+----------+------+------------+------------+----+

In [ ]:
#Liste todos os clientes cujo nome começa com a letra 'A'
# Equivalente PySpark
# Acessa o Dataframe criado anteriormente e realiza a ação



dfps = cliente_ps.filter(cliente_ps.nome.like("A%")).select('nome')

dfps.show()

+------------+
|        nome|
+------------+
|   Ana Silva|
|Alice Torres|
+------------+

In [ ]:
#5 Selecione os 3 primeiros registros da tabela cliente.
sql5 = spark.sql(
    '''
      SELECT *
      FROM clientesv
      LIMIT 3
       '''
       )

sql5.show()

+--------------+----------+------+------------+--------------+----+
|        cidade|cliente_id|estado|estado_civil|          nome|sexo|
+--------------+----------+------+------------+--------------+----+
|     Sao Paulo|         1|    SP|    Solteiro|     Ana Silva|   F|
|Rio de Janeiro|         2|    RJ|      Casado|   Bruno Souza|   M|
|Belo Horizonte|         3|    MG|    Solteiro|Carlos Pereira|   M|
+--------------+----------+------+------------+--------------+----+

In [ ]:
#5 Selecione os 3 primeiros registros da tabela cliente.
# Equivalente PySpark
# Acessa o Dataframe criado anteriormente e realiza a ação



dfps = cliente_ps.select('*').limit(3)

dfps.show()

+--------------+----------+------+------------+--------------+----+
|        cidade|cliente_id|estado|estado_civil|          nome|sexo|
+--------------+----------+------+------------+--------------+----+
|     Sao Paulo|         1|    SP|    Solteiro|     Ana Silva|   F|
|Rio de Janeiro|         2|    RJ|      Casado|   Bruno Souza|   M|
|Belo Horizonte|         3|    MG|    Solteiro|Carlos Pereira|   M|
+--------------+----------+------+------------+--------------+----+

In [ ]:
#6 Liste todos os carros que são da marca 'Ford' ou 'Fiat'.
sql6 = spark.sql(
    '''
     SELECT *
      FROM carrosv
      WHERE marca = 'Ford' OR marca = 'Fiat'
       '''
       )

sql6.show()

+--------+-----+--------+--------------------+
|carro_id|marca|  modelo|               valor|
+--------+-----+--------+--------------------+
|       1| Ford|  Fiesta|120.0000000000000...|
|       2| Ford|      Ka|110.0000000000000...|
|       3| Fiat|   Palio|100.0000000000000...|
|       4| Fiat|     Uno|90.00000000000000...|
|      14| Ford|EcoSport|160.0000000000000...|
|      15| Fiat|   Siena|120.0000000000000...|
|      16| Fiat|    Argo|130.0000000000000...|
|      19| Ford|  Ranger|250.0000000000000...|
+--------+-----+--------+--------------------+

In [ ]:
# 6 Liste todos os carros que são da marca 'Ford' ou 'Fiat'.
# Equivalente PySpark
# Acessa o Dataframe criado anteriormente e realiza a ação





dfps = carro_ps.filter((carro_ps.marca == 'Ford') | (carro_ps.marca == 'Fiat'))
dfps.show()

+--------+-----+--------+--------------------+
|carro_id|marca|  modelo|               valor|
+--------+-----+--------+--------------------+
|       1| Ford|  Fiesta|120.0000000000000...|
|       2| Ford|      Ka|110.0000000000000...|
|       3| Fiat|   Palio|100.0000000000000...|
|       4| Fiat|     Uno|90.00000000000000...|
|      14| Ford|EcoSport|160.0000000000000...|
|      15| Fiat|   Siena|120.0000000000000...|
|      16| Fiat|    Argo|130.0000000000000...|
|      19| Ford|  Ranger|250.0000000000000...|
+--------+-----+--------+--------------------+

In [ ]:
#7 Encontre todos os carros cujo valor está entre 100 e 150.
sql7 = spark.sql(
    '''
      SELECT *
      FROM carrosv
      WHERE valor
      BETWEEN 100 AND 150
       '''
       )

sql7.show()

+--------+----------+-------+--------------------+
|carro_id|     marca| modelo|               valor|
+--------+----------+-------+--------------------+
|       1|      Ford| Fiesta|120.0000000000000...|
|       2|      Ford|     Ka|110.0000000000000...|
|       3|      Fiat|  Palio|100.0000000000000...|
|       5| Chevrolet|   Onix|130.0000000000000...|
|       6| Chevrolet| Prisma|140.0000000000000...|
|       9|Volkswagen|    Gol|110.0000000000000...|
|      11|   Hyundai|   HB20|150.0000000000000...|
|      12|   Renault|Sandero|100.0000000000000...|
|      15|      Fiat|  Siena|120.0000000000000...|
|      16|      Fiat|   Argo|130.0000000000000...|
+--------+----------+-------+--------------------+

In [ ]:
# 7 Encontre todos os carros cujo valor está entre 100 e 150.
# Equivalente PySpark
# Acessa o Dataframe criado anteriormente e realiza a ação

dfps = carro_ps.filter((carro_ps.valor >= 100) & (carro_ps.valor <= 150))
dfps.show()

+--------+----------+-------+--------------------+
|carro_id|     marca| modelo|               valor|
+--------+----------+-------+--------------------+
|       1|      Ford| Fiesta|120.0000000000000...|
|       2|      Ford|     Ka|110.0000000000000...|
|       3|      Fiat|  Palio|100.0000000000000...|
|       5| Chevrolet|   Onix|130.0000000000000...|
|       6| Chevrolet| Prisma|140.0000000000000...|
|       9|Volkswagen|    Gol|110.0000000000000...|
|      11|   Hyundai|   HB20|150.0000000000000...|
|      12|   Renault|Sandero|100.0000000000000...|
|      15|      Fiat|  Siena|120.0000000000000...|
|      16|      Fiat|   Argo|130.0000000000000...|
+--------+----------+-------+--------------------+

In [ ]:
#8 Conte quantos aluguéis foram realizados
sql8 = spark.sql(
    '''
     SELECT COUNT(*)
      AS total_aluguel
      FROM alugueisv
       '''
       )

sql8.show()

+-------------+
|total_aluguel|
+-------------+
|           50|
+-------------+

In [ ]:
#8 Conte quantos aluguéis foram realizados
# Equivalente PySpark
# Acessa o Dataframe criado anteriormente e realiza a ação

NameError: name 'alugueis_df' is not defined

In [ ]:
# 9 Calcule o valor total de todos os carros disponíveis para aluguel.
sql9 = spark.sql(
    '''
      SELECT SUM(valor)
      FROM carrosv
       '''
       )

sql9.show()

+--------------------+
|          sum(valor)|
+--------------------+
|3050.000000000000...|
+--------------------+

In [ ]:
# 9 Calcule o valor total de todos os carros disponíveis para aluguel.
# Equivalente PySpark
# Acessa o Dataframe criado anteriormente e realiza a ação




dfps = carro_ps.agg(sum("valor"))
print(f"Valor total de todos os carros disponíveis para aluguel: {dfps}")

Valor total de todos os carros disponíveis para aluguel: DataFrame[sum(valor): decimal(38,18)]

In [ ]:
# 10 Calcule o valor médio dos carros.
sql10 = spark.sql(
    '''
     SELECT ROUND(AVG(valor),2)
      AS valor_medio
      FROM carrosv
       '''
       )

sql10.show()

+-----------+
|valor_medio|
+-----------+
|     152.50|
+-----------+

In [ ]:
#11 Encontre o menor e o maior valor de aluguel de carros.
sql11 = spark.sql(
    '''
       SELECT
      ROUND(MIN(valor),2) AS menor_valor,
      ROUND(MAX(valor),2) AS maior_valor
      FROM carrosv
       '''
       )

sql11.show()

+-----------+-----------+
|menor_valor|maior_valor|
+-----------+-----------+
|      90.00|     250.00|
+-----------+-----------+

In [ ]:
#12 Liste os estados diferentes presentes na tabela cliente.
sql12 = spark.sql(
    '''
      SELECT DISTINCT estado
      FROM clientesv
       '''
       )

sql12.show()

+------+
|estado|
+------+
|    SP|
|    RS|
|    MG|
|    BA|
|    PE|
|    CE|
|    RJ|
|    PR|
|    SC|
|    AM|
|    GO|
|    ES|
|    MS|
|    PA|
|    DF|
+------+

In [ ]:
#13 Agrupe os clientes por estado e conte quantos clientes existem em cada estado.
sql13 = spark.sql(
    '''
      SELECT estado,
     COUNT(*) AS numero_de_clientes
     FROM clientesv
     GROUP BY estado
       '''
       )

sql13.show()

+------+------------------+
|estado|numero_de_clientes|
+------+------------------+
|    SP|                 6|
|    RS|                 1|
|    MG|                 1|
|    BA|                 1|
|    PE|                 1|
|    CE|                 1|
|    RJ|                 1|
|    PR|                 1|
|    SC|                 1|
|    AM|                 1|
|    GO|                 1|
|    ES|                 1|
|    MS|                 1|
|    PA|                 1|
|    DF|                 1|
+------+------------------+

In [ ]:
#14 Liste os modelos de carros e o número de vezes que cada um foi alugado.
sql14 = spark.sql(

    '''
     SELECT c.modelo,
    COUNT(a.aluguel_id) AS numero_de_alugueis
    FROM alugueisv a
    JOIN carrosv c ON a.carro_id = c.carro_id
    GROUP BY c.modelo
       '''
       )

sql14.show()

+--------+------------------+
|  modelo|numero_de_alugueis|
+--------+------------------+
|   Cruze|                 2|
|   Siena|                 2|
|  Prisma|                 3|
| Compass|                 1|
|      Ka|                 3|
| Sandero|                 2|
|     Uno|                 2|
|  Fiesta|                 2|
| Corolla|                 3|
|   Civic|                 2|
|  Duster|                 3|
|    HB20|                 2|
|    HR-V|                 1|
|EcoSport|                 3|
|     Gol|                 3|
|   Jetta|                 2|
|    Onix|                 7|
|   Palio|                 2|
|  Ranger|                 3|
|    Argo|                 2|
+--------+------------------+

In [ ]:
# 15 Liste o nome dos clientes e o número de aluguéis que cada um fez
sql115 = spark.sql(
    '''
      SELECT c.nome,
      COUNT(a.aluguel_id) AS numero_de_alugueis
      FROM alugueisv a
      JOIN clientesv c ON a.cliente_id = c.cliente_id
      GROUP BY c.nome
       '''
       )



sql115.show()

+-----------------+------------------+
|             nome|numero_de_alugueis|
+-----------------+------------------+
|     Helena Rocha|                 2|
|    Luis Fernando|                 2|
|     Daniela Lima|                 3|
|   Eduardo Santos|                 4|
|    Gabriel Costa|                 3|
|        Ana Silva|                 4|
|      Igor Mendes|                 2|
|   Fernanda Alves|                 3|
|    Juliana Souza|                 3|
|     Olivia Nunes|                 2|
|     Alice Torres|                 2|
|  Queila Ferreira|                 2|
|    Sofia Martins|                 2|
|     Thiago Lopes|                 2|
|    Nuno Oliveira|                 2|
|   Carlos Pereira|                 2|
|Ricardo Goncalves|                 2|
|      Pedro Ramos|                 2|
|     Mariana Dias|                 2|
|      Bruno Souza|                 4|
+-----------------+------------------+

In [ ]:
# 16 Liste todos os aluguéis, mostrando o nome do cliente e o modelo do carro alugado.
sql16 = spark.sql(
    '''
      SELECT a.aluguel_id, cl.nome, c.modelo
    FROM alugueisv a
    JOIN clientesv cl ON a.cliente_id = cl.cliente_id
    JOIN carrosv c ON a.carro_id = c.carro_id;
       '''
       )

sql16.show()

+----------+-----------------+-------+
|aluguel_id|             nome| modelo|
+----------+-----------------+-------+
|        50|     Alice Torres|Corolla|
|        39|      Pedro Ramos|Corolla|
|        15|   Eduardo Santos|Corolla|
|        41|  Queila Ferreira| Prisma|
|        33|     Mariana Dias| Prisma|
|        25|     Helena Rocha| Prisma|
|        46|    Sofia Martins|    Gol|
|        32|    Luis Fernando|    Gol|
|        23|    Gabriel Costa|    Gol|
|        43|Ricardo Goncalves|   Onix|
|        28|    Juliana Souza|   Onix|
|        20|   Fernanda Alves|   Onix|
|        11|     Daniela Lima|   Onix|
|        10|   Carlos Pereira|   Onix|
|         8|      Bruno Souza|   Onix|
|         1|        Ana Silva|   Onix|
|        31|    Luis Fernando| Fiesta|
|        27|      Igor Mendes| Fiesta|
|        36|    Nuno Oliveira|  Jetta|
|        16|   Eduardo Santos|  Jetta|
+----------+-----------------+-------+
only showing top 20 rows

In [ ]:
# 17 Encontre os clientes que alugaram o carro com modelo 'Onix'.
sql17 = spark.sql(
    '''
    SELECT cl.cliente_id, cl.nome
    FROM alugueisv a
    JOIN clientesv cl ON a.cliente_id = cl.cliente_id
    JOIN carrosv c ON a.carro_id = c.carro_id
    WHERE c.modelo = 'Onix';
       '''
       )

sql17.show()

+----------+-----------------+
|cliente_id|             nome|
+----------+-----------------+
|        17|Ricardo Goncalves|
|        10|    Juliana Souza|
|         6|   Fernanda Alves|
|         4|     Daniela Lima|
|         3|   Carlos Pereira|
|         2|      Bruno Souza|
|         1|        Ana Silva|
+----------+-----------------+

In [ ]:
# 18 Liste os nomes dos clientes e as datas em que alugaram carros.
sql18 = spark.sql(
    '''
    SELECT c.nome, a.data_aluguel
    FROM alugueisv a
    JOIN clientesv c
    ON a.cliente_id = c.cliente_id
       '''
       )

sql18.show()

+--------------+------------+
|          nome|data_aluguel|
+--------------+------------+
|     Ana Silva|  2023-08-15|
|     Ana Silva|  2023-09-01|
|     Ana Silva|  2023-09-10|
|     Ana Silva|  2023-09-21|
|   Bruno Souza|  2023-07-30|
|   Bruno Souza|  2023-08-10|
|   Bruno Souza|  2023-09-02|
|   Bruno Souza|  2023-09-25|
|Carlos Pereira|  2023-06-15|
|Carlos Pereira|  2023-09-05|
|  Daniela Lima|  2023-09-20|
|  Daniela Lima|  2023-08-18|
|  Daniela Lima|  2023-09-22|
|Eduardo Santos|  2023-07-20|
|Eduardo Santos|  2023-08-05|
|Eduardo Santos|  2023-09-15|
|Eduardo Santos|  2023-09-28|
|Fernanda Alves|  2023-08-08|
|Fernanda Alves|  2023-09-03|
|Fernanda Alves|  2023-09-28|
+--------------+------------+
only showing top 20 rows

In [ ]:
# 19 Encontre o nome dos clientes e os modelos de carros que alugaram
sql19 = spark.sql(
    '''
    SELECT cli.nome, c.modelo
    FROM alugueisv a
    JOIN clientesv cli
    ON a.cliente_id = cli.cliente_id
    JOIN carrosv c
    ON a.carro_id = c.carro_id
       '''
       )

sql19.show()

+-----------------+-------+
|             nome| modelo|
+-----------------+-------+
|     Alice Torres|Corolla|
|      Pedro Ramos|Corolla|
|   Eduardo Santos|Corolla|
|  Queila Ferreira| Prisma|
|     Mariana Dias| Prisma|
|     Helena Rocha| Prisma|
|    Sofia Martins|    Gol|
|    Luis Fernando|    Gol|
|    Gabriel Costa|    Gol|
|Ricardo Goncalves|   Onix|
|    Juliana Souza|   Onix|
|   Fernanda Alves|   Onix|
|     Daniela Lima|   Onix|
|   Carlos Pereira|   Onix|
|      Bruno Souza|   Onix|
|        Ana Silva|   Onix|
|    Luis Fernando| Fiesta|
|      Igor Mendes| Fiesta|
|    Nuno Oliveira|  Jetta|
|   Eduardo Santos|  Jetta|
+-----------------+-------+
only showing top 20 rows

In [ ]:
#20 Crie uma consulta que retorne o nome dos clientes e uma coluna adicional chamada status_civil que classifica os clientes como "Solteiro" ou "Casado".
sql20 = spark.sql(
    '''
    SELECT cli.nome,
    CASE WHEN cli.estado_civil = 'Solteiro' THEN 'Solteiro'
    WHEN cli.estado_civil = 'Casado' THEN 'Casado'
    ELSE 'Outro'
    END AS status_civil
    FROM clientesv cli
       '''
       )

sql20.show()

+-----------------+------------+
|             nome|status_civil|
+-----------------+------------+
|        Ana Silva|    Solteiro|
|      Bruno Souza|      Casado|
|   Carlos Pereira|    Solteiro|
|     Daniela Lima|      Casado|
|   Eduardo Santos|    Solteiro|
|   Fernanda Alves|      Casado|
|    Gabriel Costa|    Solteiro|
|     Helena Rocha|    Solteiro|
|      Igor Mendes|      Casado|
|    Juliana Souza|    Solteiro|
|    Luis Fernando|    Solteiro|
|     Mariana Dias|      Casado|
|    Nuno Oliveira|      Casado|
|     Olivia Nunes|    Solteiro|
|      Pedro Ramos|    Solteiro|
|  Queila Ferreira|      Casado|
|Ricardo Goncalves|      Casado|
|    Sofia Martins|    Solteiro|
|     Thiago Lopes|      Casado|
|     Alice Torres|    Solteiro|
+-----------------+------------+